const quotes = [
    {"name": "Word: Aberration", "quote": "Meaning:&#x275D A departure from what is normal or expected &#x275E"},
    {"name": "Word: Belligerent", "quote": "Meaning:&#x275D Hostile and aggressive &#x275E"},
    {"name": "Word: Cacophony", "quote": "Meaning:&#x275D A harsh, discordant mixture of sounds &#x275E"},
    {"name": "Word: Dauntless", "quote": "Meaning:&#x275D Showing fearlessness and determination &#x275E"},
    {"name": "Word: Eloquent", "quote": "Meaning:&#x275D Fluent or persuasive in speaking or writing &#x275E"},
    {"name": "Word: Furtive", "quote": "Meaning:&#x275D Attempting to avoid notice or attention; secretive &#x275E"},
    {"name": "Word: Gregarious", "quote": "Meaning:&#x275D Fond of company; sociable &#x275E"},
    {"name": "Word: Hapless", "quote": "Meaning:&#x275D Unfortunate or unlucky &#x275E"},
    {"name": "Word: Ineffable", "quote": "Meaning:&#x275D Too great or extreme to be expressed in words &#x275E"},
    {"name": "Word: Juxtaposition", "quote": "Meaning:&#x275D The fact of two things being seen or placed close together with contrasting effect &#x275E"},
    {"name": "Word: Kowtow", "quote": "Meaning:&#x275D Act in an excessively subservient manner &#x275E"},
    {"name": "Word: Laconic", "quote": "Meaning:&#x275D Using very few words; concise &#x275E"},
    {"name": "Word: Mirth", "quote": "Meaning:&#x275D Amusement, especially as expressed in laughter &#x275E"},
    {"name": "Word: Nefarious", "quote": "Meaning:&#x275D Wicked or criminal &#x275E"},
    {"name": "Word: Obstreperous", "quote": "Meaning:&#x275D Noisy and difficult to control &#x275E"},
    {"name": "Word: Parsimonious", "quote": "Meaning:&#x275D Extremely unwilling to spend money or resources &#x275E"},
    {"name": "Word: Quintessential", "quote": "Meaning:&#x275D Representing the most perfect or typical example of a quality or class &#x275E"},
    {"name": "Word: Resplendent", "quote": "Meaning:&#x275D Attractive and impressive through being richly colorful or sumptuous &#x275E"},
    {"name": "Word: Sanguine", "quote": "Meaning:&#x275D Optimistic or positive, especially in a bad situation &#x275E"},
    {"name": "Word: Tenuous", "quote": "Meaning:&#x275D Very weak or slight &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"},
    {"name": "Word: Ubiquitous", "quote": "Meaning:&#x275D Present, appearing, or found everywhere &#x275E"},
    {"name": "Word: Voracious", "quote": "Meaning:&#x275D Wanting or devouring great quantities of food &#x275E"},
    {"name": "Word: Winsome", "quote": "Meaning:&#x275D Attractive or appealing in a fresh, innocent way &#x275E"},
    {"name": "Word: Xenophobic", "quote": "Meaning:&#x275D Having a dislike of or prejudice against people from other countries &#x275E"},
    {"name": "Word: Yearn", "quote": "Meaning:&#x275D Have an intense feeling of longing for something &#x275E"},
    {"name": "Word: Zealous", "quote": "Meaning:&#x275D Having great energy or enthusiasm for a cause or objective &#x275E"},
    {"name": "Word: Ascetic", "quote": "Meaning:&#x275D Practicing strict self-discipline and abstention from indulgence &#x275E"},
    {"name": "Word: Blithe", "quote": "Meaning:&#x275D Showing a casual and cheerful indifference considered to be callous &#x275E"},
    {"name": "Word: Capitulate", "quote": "Meaning:&#x275D Cease to resist an opponent; surrender &#x275E"},
    {"name": "Word: Dichotomy", "quote": "Meaning:&#x275D A division or contrast between two things &#x275E"},
    {"name": "Word: Ephemeral", "quote": "Meaning:&#x275D Lasting for a very short time &#x275E"},
    {"name": "Word: Felicitous", "quote": "Meaning:&#x275D Well chosen or suited to the circumstances &#x275E"},
    {"name": "Word: Grandiloquent", "quote": "Meaning:&#x275D Pompous or extravagant in language, style, or manner &#x275E"},
    {"name": "Word: Harangue", "quote": "Meaning:&#x275D A lengthy and aggressive speech &#x275E"},
    {"name": "Word: Insidious", "quote": "Meaning:&#x275D Proceeding in a gradual, subtle way, but with harmful effects &#x275E"},
    {"name": "Word: Juxtapose", "quote": "Meaning:&#x275D Place or deal with close together for contrasting effect &#x275E"},
    {"name": "Word: Loquacious", "quote": "Meaning:&#x275D Tending to talk a great deal; talkative &#x275E"},
    {"name": "Word: Mollify", "quote": "Meaning:&#x275D Appease the anger or anxiety of someone &#x275E"},
    {"name": "Word: Nostalgia", "quote": "Meaning:&#x275D A sentimental longing for the past &#x275E"},
    {"name": "Word: Obfuscate", "quote": "Meaning:&#x275D Render obscure, unclear, or unintelligible &#x275E"}
]
const quoteBtn = document.querySelector('#quoteBtn');
const quoteAuthor = document.querySelector('#quoteAuthor');
const quote = document.querySelector('#quote');


quoteBtn.addEventListener('click', displayQuote);

function displayQuote() {
    let number = Math.floor(Math.random() * quotes.length);
    quoteAuthor.innerHTML = quotes[number].quote;
    quote.innerHTML = quotes[number].name;
}
